services:

  nginx:
    image: nginx:1.17-alpine
    container_name: boil_nginx
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - php

  code:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php-dev
    container_name: boil_code
    volumes:
      - ./:/app:rw,delegated
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /app/var/
      - /app/var/cache/
      - /app/var/logs/
      - /app/var/sessions/

  php:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php-dev
    container_name: boil_php
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CLIENT_HOST=host.docker.internal
    volumes:
      - ./:/app:rw,delegated
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /app/var/
      - /app/var/cache/
      - /app/var/logs/
      - /app/var/sessions/
    depends_on:
      - mysql
      - rmq
      - elasticsearch

  workers_events:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php-dev
    container_name: boil_wk_events
    volumes:
      - ./:/app:rw,delegated
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /app/var/
      - /app/var/cache/
      - /app/var/logs/
      - /app/var/sessions/
    command: ['/app/bin/console', 'messenger:consume', 'events', '-vv']
    depends_on:
      - mysql
      - rmq
      - elasticsearch
    restart: always

  workers_users:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php-dev
    container_name: boil_wk_users
    volumes:
      - ./:/app:rw,delegated
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /app/var/
      - /app/var/cache/
      - /app/var/logs/
      - /app/var/sessions/
    command: ['/app/bin/console', 'messenger:consume', 'users', '-vv']
    depends_on:
      - mysql
      - rmq
      - elasticsearch
    restart: always

  mysql:
    image: mysql:8.0.33
    container_name: boil_mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3308:3306"
    volumes:
     - "./etc/ci/mysql:/etc/mysql/conf.d"
    tmpfs:
     - /var/lib/mysql/:rw,noexec,nosuid,size=600m
     - /tmp/:rw,noexec,nosuid,size=50m
    environment:
      - MYSQL_PASSWORD=api
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_USER=cqrs
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: boil_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: api
    ports:
      - "8780:80"
    depends_on:
      - mysql

  rmq:
    image: rabbitmq:3-management
    container_name: boil_rmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: boil_elastik
    environment:
      - "discovery.type=single-node"
      - "cluster.name=sf-events"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    container_name: boil_start_deps
    depends_on:
      - mysql
      - rmq
      - elasticsearch
    command: mysql:3306 elasticsearch:9200 rmq:5672
